CREATE TABLE IF NOT EXISTS file_snaps (
  id INTEGER PRIMARY KEY,
  path_id INTEGER NULL,
  file_name VARCHAR NOT NULL,
  modified UNSIGNED BIGINT NOT NULL,
  size UNSIGNED BIGINT NOT NULL,
  record_date UNSIGNED BIGINT NOT NULL,
  FOREIGN KEY(path_id) REFERENCES paths(id)
);

CREATE TABLE IF NOT EXISTS paths (
  id INTEGER PRIMARY KEY,
  path VARCHAR NOT NULL UNIQUE
);