CREATE TABLE IF NOT EXISTS file_snaps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  path VARCHAR NOT NULL,
  modified UNSIGNED BIGINT NOT NULL,
  size UNSIGNED BIGINT NOT NULL,
  record_date UNSIGNED BIGINT NOT NULL);
