CREATE TABLE IF NOT EXISTS file_snaps (
  id INTEGER PRIMARY KEY,
  name_id INTEGER NOT NULL,
  modified UNSIGNED BIGINT NOT NULL,
  size UNSIGNED BIGINT NOT NULL,
  record_date UNSIGNED BIGINT NOT NULL,
  FOREIGN KEY(name_id) REFERENCES file_names(id)
);

CREATE TABLE IF NOT EXISTS file_names (
  id INTEGER PRIMARY KEY,
  file_name BLOB NOT NULL UNIQUE
);